Repository Elemental-Edge/Clue_less, pull requests merged in 2024-10, with the labels that each got.

#4 Client Server Model Framework
  .gitignore
  Backend/Authentication/__init__.py
  Backend/Authentication/admin.py
  Backend/Authentication/apps.py
  Backend/Authentication/migrations/__init__.py
  Backend/Authentication/models.py
  Backend/Authentication/tests.py
  Backend/Authentication/views.py
  Backend/GameManagement/__init__.py
  Backend/GameManagement/admin.py
  Backend/GameManagement/apps.py
  Backend/GameManagement/migrations/0001_initial.py
  Backend/GameManagement/migrations/0002_card_person_player_gamesession_roomhallway_and_more.py
  Backend/GameManagement/migrations/__init__.py
  Backend/GameManagement/models.py
  Backend/GameManagement/tests.py
  Backend/GameManagement/views.py
  Backend/MessageTranslator/__init__.py
  Backend/MessageTranslator/admin.py
  Backend/MessageTranslator/apps.py
  Backend/MessageTranslator/consumers.py
  Backend/MessageTranslator/migrations/0001_initial.py
  Backend/MessageTranslator/migrations/__init__.py
  Backend/MessageTranslator/models.py
  Backend/MessageTranslator/routing.py
  Backend/MessageTranslator/tests.py
  Backend/MessageTranslator/views.py
  Backend/__init__.py
  Frontend/ClientCli.py
  Frontend/ClientIF.py
  Frontend/__init__.py
  README.md
  clue_less/__init__.py
  clue_less/asgi.py
  clue_less/settings.py
  clue_less/urls.py
  clue_less/wsgi.py
  manage.py
Labels: documentation, enhancement, good first issue

#16 Create Django test work flow
  .github/workflows/python-app.yml
  Frontend/ClientCli.py
  clue_env_release.yml
Labels: CICD

#17 added some basic test case for the Authentication views and GameManagement models. Will attempt to add more test cases for frontend and MessageTranslator.
  Backend/Authentication/tests.py
  Backend/GameManagement/tests.py
  README.md
Labels: enhancement
